<a href="https://colab.research.google.com/github/Raoolo/University/blob/main/DeepMachineLearning/Lab1Ex3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
t1 = torch.rand(size=(3,3,3,3))
t2 = torch.rand(size=(3,3,3,3))

In [2]:
t1.dtype

torch.float32

In [3]:
t1.cuda()
t2.cuda()

tensor([[[[9.3201e-01, 2.8975e-01, 1.2700e-01],
          [4.3206e-02, 2.6524e-01, 1.9309e-01],
          [6.3246e-01, 5.6460e-01, 3.7632e-01]],

         [[1.4757e-01, 1.5137e-02, 9.9177e-01],
          [2.3997e-01, 4.2224e-01, 2.5528e-02],
          [2.5056e-01, 9.4824e-02, 8.4066e-01]],

         [[5.4161e-01, 5.3155e-01, 6.2157e-01],
          [3.4481e-01, 9.4226e-01, 4.4475e-01],
          [4.3589e-01, 5.7813e-01, 7.7328e-01]]],


        [[[2.8937e-01, 9.4282e-01, 7.0591e-02],
          [2.0621e-01, 3.1590e-01, 8.7621e-01],
          [2.5843e-01, 8.3462e-01, 8.1867e-01]],

         [[1.1378e-01, 2.8273e-01, 3.6443e-01],
          [1.9893e-01, 6.8052e-01, 4.8934e-01],
          [4.0207e-01, 9.2652e-01, 8.9405e-02]],

         [[3.6154e-01, 8.0845e-01, 8.4476e-01],
          [8.1833e-01, 5.8113e-01, 3.6621e-01],
          [4.6811e-01, 5.7685e-02, 6.1152e-01]]],


        [[[8.3781e-01, 7.3210e-01, 8.8066e-02],
          [1.7794e-01, 8.3981e-01, 8.4871e-01],
          [4.3031e-01, 2

In [4]:
t3 = torch.sum(t1)
t3

tensor(34.6705)

In [5]:
t4 = torch.add(t1, t2)
t4

tensor([[[[1.4583, 0.4081, 0.2047],
          [0.8054, 0.6012, 0.2724],
          [0.6546, 1.0208, 0.4797]],

         [[0.8308, 0.5661, 1.4978],
          [0.3617, 0.4428, 0.6200],
          [0.6895, 0.9614, 1.1424]],

         [[1.3085, 0.7370, 1.2135],
          [0.4089, 1.6185, 1.0558],
          [1.2443, 0.8572, 0.9265]]],


        [[[0.9386, 1.8526, 0.6645],
          [0.9529, 0.6755, 0.9416],
          [0.3128, 1.1592, 1.4229]],

         [[0.1308, 0.5643, 0.3892],
          [0.2810, 1.3849, 1.2282],
          [0.4415, 1.1571, 0.2209]],

         [[1.0331, 1.5463, 1.4044],
          [1.6443, 0.8768, 0.5381],
          [0.5471, 0.8274, 1.5549]]],


        [[[1.7729, 1.1403, 0.2562],
          [0.4706, 1.4180, 1.0305],
          [0.5606, 0.2529, 0.4062]],

         [[1.2573, 0.1241, 0.7342],
          [1.3151, 0.4704, 0.5476],
          [1.1925, 1.8490, 1.5217]],

         [[0.9587, 1.3347, 0.7471],
          [0.3068, 1.4997, 0.6696],
          [1.7659, 1.5272, 1.2531]]]])

In [6]:
t5 = t1 + t2
t5    #same of add

tensor([[[[1.4583, 0.4081, 0.2047],
          [0.8054, 0.6012, 0.2724],
          [0.6546, 1.0208, 0.4797]],

         [[0.8308, 0.5661, 1.4978],
          [0.3617, 0.4428, 0.6200],
          [0.6895, 0.9614, 1.1424]],

         [[1.3085, 0.7370, 1.2135],
          [0.4089, 1.6185, 1.0558],
          [1.2443, 0.8572, 0.9265]]],


        [[[0.9386, 1.8526, 0.6645],
          [0.9529, 0.6755, 0.9416],
          [0.3128, 1.1592, 1.4229]],

         [[0.1308, 0.5643, 0.3892],
          [0.2810, 1.3849, 1.2282],
          [0.4415, 1.1571, 0.2209]],

         [[1.0331, 1.5463, 1.4044],
          [1.6443, 0.8768, 0.5381],
          [0.5471, 0.8274, 1.5549]]],


        [[[1.7729, 1.1403, 0.2562],
          [0.4706, 1.4180, 1.0305],
          [0.5606, 0.2529, 0.4062]],

         [[1.2573, 0.1241, 0.7342],
          [1.3151, 0.4704, 0.5476],
          [1.1925, 1.8490, 1.5217]],

         [[0.9587, 1.3347, 0.7471],
          [0.3068, 1.4997, 0.6696],
          [1.7659, 1.5272, 1.2531]]]])

In [7]:
t6 = t1 @ t2
t6    #same of matmul

tensor([[[[0.5448, 0.2278, 0.1189],
          [0.7751, 0.3548, 0.1915],
          [0.1057, 0.1858, 0.1298]],

         [[0.3598, 0.2910, 1.1170],
          [0.1718, 0.0669, 0.6210],
          [0.3483, 0.4012, 0.7111]],

         [[0.7442, 0.9434, 1.0258],
          [0.5342, 1.0245, 0.8131],
          [0.6009, 0.7813, 0.7451]]],


        [[[0.5290, 1.3952, 1.3292],
          [0.3071, 0.8722, 0.4214],
          [0.2388, 0.6581, 0.7829]],

         [[0.0679, 0.2194, 0.1462],
          [0.4465, 1.1871, 0.4406],
          [0.1032, 0.2899, 0.1390]],

         [[1.1086, 1.0040, 1.1798],
          [0.6210, 0.8495, 0.9111],
          [1.1001, 0.5656, 0.9255]]],


        [[[0.9284, 1.0655, 0.4288],
          [0.4263, 0.7410, 0.5165],
          [0.2886, 0.2094, 0.0336]],

         [[0.5622, 0.2120, 0.6388],
          [0.4788, 0.1890, 0.4798],
          [1.3767, 0.9022, 1.2042]],

         [[0.7501, 1.1544, 0.6194],
          [0.5683, 0.9591, 0.5144],
          [1.1090, 1.5250, 0.8148]]]])

In [8]:
t9 = torch.matmul(t1, t2)
t9

tensor([[[[0.5448, 0.2278, 0.1189],
          [0.7751, 0.3548, 0.1915],
          [0.1057, 0.1858, 0.1298]],

         [[0.3598, 0.2910, 1.1170],
          [0.1718, 0.0669, 0.6210],
          [0.3483, 0.4012, 0.7111]],

         [[0.7442, 0.9434, 1.0258],
          [0.5342, 1.0245, 0.8131],
          [0.6009, 0.7813, 0.7451]]],


        [[[0.5290, 1.3952, 1.3292],
          [0.3071, 0.8722, 0.4214],
          [0.2388, 0.6581, 0.7829]],

         [[0.0679, 0.2194, 0.1462],
          [0.4465, 1.1871, 0.4406],
          [0.1032, 0.2899, 0.1390]],

         [[1.1086, 1.0040, 1.1798],
          [0.6210, 0.8495, 0.9111],
          [1.1001, 0.5656, 0.9255]]],


        [[[0.9284, 1.0655, 0.4288],
          [0.4263, 0.7410, 0.5165],
          [0.2886, 0.2094, 0.0336]],

         [[0.5622, 0.2120, 0.6388],
          [0.4788, 0.1890, 0.4798],
          [1.3767, 0.9022, 1.2042]],

         [[0.7501, 1.1544, 0.6194],
          [0.5683, 0.9591, 0.5144],
          [1.1090, 1.5250, 0.8148]]]])

In [9]:
t7 = t1 * t2
t7    #same of mul

tensor([[[[4.9052e-01, 3.4302e-02, 9.8663e-03],
          [3.2933e-02, 8.9109e-02, 1.5319e-02],
          [1.4005e-02, 2.5755e-01, 3.8906e-02]],

         [[1.0082e-01, 8.3397e-03, 5.0186e-01],
          [2.9213e-02, 8.6916e-03, 1.5175e-02],
          [1.0997e-01, 8.2176e-02, 2.5367e-01]],

         [[4.1537e-01, 1.0919e-01, 3.6794e-01],
          [2.2108e-02, 6.3718e-01, 2.7177e-01],
          [3.5240e-01, 1.6136e-01, 1.1849e-01]]],


        [[[1.8787e-01, 8.5780e-01, 4.1923e-02],
          [1.5397e-01, 1.1361e-01, 5.7329e-02],
          [1.4046e-02, 2.7094e-01, 4.9464e-01]],

         [[1.9379e-03, 7.9605e-02, 9.0251e-03],
          [1.6336e-02, 4.7933e-01, 3.6153e-01],
          [1.5871e-02, 2.1362e-01, 1.1758e-02]],

         [[2.4281e-01, 5.9654e-01, 4.7278e-01],
          [6.7588e-01, 1.7182e-01, 6.2943e-02],
          [3.6974e-02, 4.4403e-02, 5.7690e-01]]],


        [[[7.8344e-01, 2.9881e-01, 1.4806e-02],
          [5.2080e-02, 4.8553e-01, 1.5428e-01],
          [5.6078e-02, 5

In [10]:
t8 = torch.mul(t1, t2)
t8

tensor([[[[4.9052e-01, 3.4302e-02, 9.8663e-03],
          [3.2933e-02, 8.9109e-02, 1.5319e-02],
          [1.4005e-02, 2.5755e-01, 3.8906e-02]],

         [[1.0082e-01, 8.3397e-03, 5.0186e-01],
          [2.9213e-02, 8.6916e-03, 1.5175e-02],
          [1.0997e-01, 8.2176e-02, 2.5367e-01]],

         [[4.1537e-01, 1.0919e-01, 3.6794e-01],
          [2.2108e-02, 6.3718e-01, 2.7177e-01],
          [3.5240e-01, 1.6136e-01, 1.1849e-01]]],


        [[[1.8787e-01, 8.5780e-01, 4.1923e-02],
          [1.5397e-01, 1.1361e-01, 5.7329e-02],
          [1.4046e-02, 2.7094e-01, 4.9464e-01]],

         [[1.9379e-03, 7.9605e-02, 9.0251e-03],
          [1.6336e-02, 4.7933e-01, 3.6153e-01],
          [1.5871e-02, 2.1362e-01, 1.1758e-02]],

         [[2.4281e-01, 5.9654e-01, 4.7278e-01],
          [6.7588e-01, 1.7182e-01, 6.2943e-02],
          [3.6974e-02, 4.4403e-02, 5.7690e-01]]],


        [[[7.8344e-01, 2.9881e-01, 1.4806e-02],
          [5.2080e-02, 4.8553e-01, 1.5428e-01],
          [5.6078e-02, 5

In [16]:
t10 = torch.cat((t1, t2), axis=3)
t10.size()

torch.Size([3, 3, 3, 6])